### DISCUSSION TITLE
Add new Language Model

### DISCUSSION THREAD

**Discussion by manducagiuseppe** [bionic-gpt/bionic-gpt#232] [Q&A]
I'm not understanding such a thing as adding new language models.
for example how do I add this model? https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1

Thanks

**Comment by ianpurton** [comment]
Do you have enough hardware to run it?

**Comment by manducagiuseppe** [comment]
Yes,i have a NVIDIA A100 Graphics 80gb

**Comment by ianpurton** [comment]
The first step would be to get the model running in TGI - https://github.com/huggingface/text-generation-inference

This will give then an API. If you get that running you can follow this guide. https://bionic-gpt.com/docs/running-locally/gpu-setup/

We're very interested in seeing this work as we would like to use 8x7B as our production setup.

We can also setup a call if you like. You can contact us here https://www.linkedin.com/in/ianpurton/

**Comment by kulbinderdio** [comment]
Hopefully these steps will make it a bit easier

```
curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose-gpu.yml
```

Once this has been downloaded. Edit it to change the model. Afterwards the file should look like this
```
services:

  tgi:
    image: ghcr.io/huggingface/text-generation-inference:1.2
    command: --model-id  mistralai/Mixtral-8x7B-Instruct-v0.1 --max-batch-prefill-tokens 2048 --quantize bitsandbytes-nf4  
    volumes:
      - ./models:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  llm-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    
    command:
      - /bin/sh
      - -c
      - |
        pip install async_generator
        litellm --model huggingface/mistralai/Mixtral-8x7B-Instruct-v0.1 --api_base http://tgi/generate_stream --host 0.0.0.0 --port 3000
    entrypoint: []
    ports:
      - "3000:3000"    
    platform: linux/amd64
```
if you then run
```
docker compose -f docker-compose-gpu.yml up
```
This will download the TGI docker image (if you don't have it) and start to download the model files, you will see messages such as 
```
bionic-tgi-1      | 2023-12-18T13:05:13.716568Z  INFO text_generation_launcher: Download file: model-00001-of-00019.safetensors
```

Depending on your network speed this could take some time.

Once finished downloading I would stop this service and start up bionicGPT using the following command
```
docker compose -f docker-compose.yml -f docker-compose-gpu.yml up
```

Let me know if you're prefer to have a call. You can contact me on https://www.linkedin.com/in/kulbinderdio/
