### DISCUSSION TITLE
Using the built in Postgres DB to create reports and user audit trails

### DISCUSSION THREAD

**Discussion by tbendien** [bionic-gpt/bionic-gpt#238] [Show and tell]
After you run the pgadmin yaml you can start querying the Postgres logs to run reports and user analytics, possibly also start using  prompts and responses for creating datasets for tuning. 

Create a file called "docker-compose-pgadmin.yml" in the directory where you run the yaml to launch the Bionic containers.

Here is the yaml to insert in the file:

```
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
```

Here is a sample query to provide a user activity report:

```sql
select 
  chats.created_at,
  status,
  email,
  first_name, 
  last_name,
  user_request,
  response
from users
join conversations on users.id = conversations.user_id  
join chats on chats.conversation_id = conversations.id
```
