### DISCUSSION TITLE
Installing on Portainer (Docker UI)

### DISCUSSION THREAD

**Discussion by cdarv** [bionic-gpt/bionic-gpt#243] [General]
Hey there, I'm not sure about the demand of this because I didn't see any other discussion surrounding it, but I happened to have Portainer for some of my other services, and wanted to check out bionicGPT. 

There were a couple of small issues on setting up the stack compared to just running `docker-compose up` that I ran into and was able to fix with a couple small changes to the compose.yml file. If anyone is interested in having this as a compose file in the project i'm happy to contribute it, but for now I'll just post it here.

the two minor changes were creating a volume for the persistent data in Portainer, and putting an this environment variable under the app service:

```
  environment:
    APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
```

Below is the full file that got me up and running, able to register my admin account and begin to chat with a bot. I can test out more features as I'm learning. Hope this helps!

```
services:

  llm-api:
    image: ghcr.io/bionic-gpt/llama-2-7b-chat:1.0.4
    platform: linux/amd64

  embeddings-api:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.2.2
    platform: linux/amd64
    command: --model-id BAAI/bge-small-en-v1.5

  # Handles parsing of multiple documents types.
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:c30a2b8
    platform: linux/amd64
    ports:
      - "8000:8000"

  # Handles routing between the application, barricade and the LLM API
  envoy:
    image: ghcr.io/bionic-gpt/bionicgpt-envoy:1.4.14
    platform: linux/amd64
    ports:
      - "7800:7700"

  # Postgres pre-loaded with pgVector
  # To connect outside docker `docker compose exec db psql -U postgres`
  db:
    image: ankane/pgvector
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: finetuna
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sets up our database tables
  migrations:
    image: ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.4.14
    platform: linux/amd64
    environment:
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  # Barricade handles all /auth routes for user sign up and sign in.
  barricade:
    image: purtontech/barricade
    platform: linux/amd64
    environment:
        # This secret key is used to encrypt cookies.
        SECRET_KEY: 190a5bf4b3cbb6c0991967ab1c48ab30790af876720f1835cbbf3820f4f5d949
        DATABASE_URL: postgresql://ft_authentication:testpassword@db:5432/postgres?sslmode=disable
        FORWARD_URL: app
        FORWARD_PORT: 7703
        REDIRECT_URL: /app/post_registration
        RUST_LOG: warn
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  # Our axum server delivering our user interface
  pipeline-job:
    image: ghcr.io/bionic-gpt/bionicgpt-pipeline-job:1.4.14
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  # Our axum server delivering our user interface
  app:
    image: ghcr.io/bionic-gpt/bionicgpt:1.4.14
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable

volumes:
  dbdata:
```
