### DISCUSSION TITLE
Azure AD OIDC Authentication - Didn't find an authentication header

### DISCUSSION THREAD

**Discussion by bsu3338** [bionic-gpt/bionic-gpt#327] [General]
### Describe your issue

I am trying to use Azure AD Authentication instead of KeyCloak.  

oauth2/userinfo returns an empty username, but it does have correct values for email and groups.
https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints

If I set the value for OAUTH2_PROXY_PREFER_EMAIL_TO_USER, then it uses the email in the X-FORWARDED-USER.  However, I cannot get oauth2-proxy to return both X-FORWARDED-EMAIL and X-FORWARDED-USER.  It only seems to return one or the other.
I think it may be connected to the below entries in the oauth2-proxy CHANGELOG
[#537](https://github.com/oauth2-proxy/oauth2-proxy/pull/537) Drop Fallback to Email if User not set
  - Previously, when a session was loaded, if the User was not set, it would be replaced by the Email.
    This behaviour was inconsistent as it required the session to be stored and then loaded to function properly.
  - This behaviour has now been removed and the User field will remain empty if it was not set when the session was saved.
  - In some scenarios `X-Forwarded-User` will now be empty. Use `X-Forwarded-Email` instead.
  - In some scenarios, this may break setting Basic Auth on upstream or responses.
    Use `--prefer-email-to-user` to restore falling back to the Email in these cases.

Once, I authenticate. I receive "Didn't find an authentication header", but I can go to /oauth2/userinfo and view that my email and groups are set.

### Describe your setup/startup scripts

I removed references to keyclock and followed the instructions from 

https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#azure-auth-provider
NOTE: I followed V2 Azure Auth endpoint settings

OAUTH2_PROXY_PROVIDER: azure
OAUTH2_PROXY_AZURE_TENANT: 
OAUTH2_PROXY_AZURE_GRAPH_GROUP_FIELD: "displayName"
OAUTH2_PROXY_SESSION_COOKIE_MINIMAL: "true"
OAUTH2_PROXY_SCOPE: "openid email"

### Steps to reproduce

See setup scripts

### What was the expected result?

I would hope to authenticate with Azure AD

### Any additional information

I know this is still a really new feature, and I do not mind troubleshooting.

**Comment by ianpurton** [comment]
So I guess we could just rely on `X-Forwarded-Email`

Let me check, Keycloak populates `X-Forwarded-User` with it's own kind of ID. This actually gives us problems if people reset the system and forget to clear cookies.

So I could fix it to use `X-Forwarded-Email` but then what happens if a user changes their email address?

I need to do some research.

**Comment by bsu3338** [comment]
I have not tried using the new alpha config way of configuring oauth2-proxy. It could be possible that way to have both user and email. I was just trying to use env variables.

**Comment by bsu3338** [comment]
I was able to make it work, but not for sure if there was not an easier way.  I used a combination of env and alpha config file.  It might have been possible with just using the OIDC provider vs the azure.  Just making some notes here in case anyone else ran into the problem. Note: I also used oath2-proxy for SSL termination.

I used the solution from the below link to help me configure the oidc provider with azure information
https://github.com/oauth2-proxy/oauth2-proxy/issues/1666#issuecomment-1803920565


from docker-compose:
```
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    platform: linux/amd64
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: RandomString
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_REDIRECT_URL: https://FQDN/oauth2/callback
      OAUTH2_PROXY_SESSION_COOKIE_MINIMAL: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
    restart: unless-stopped
    command: --alpha-config /etc/oauth2-proxy/config.yaml
    volumes:
      - /srv/oauth2-proxy/config/config.yaml:/etc/oauth2-proxy/config.yaml:ro
      - /srv/oauth2-proxy/config/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /srv/oauth2-proxy/config/privkey.pem:/etc/ssl/private/privkey.pem:ro
    ports:
      - 443:443
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
```

from config.yaml:
```
UpstreamConfig:
  upstreams:
  - flushInterval: 1s
    id: /
    passHostHeader: true
    path: /
    proxyWebSockets: true
    timeout: 30s
    uri: http://app:7703
injectRequestHeaders:
- name: X-Forwarded-Groups
  values:
  - claim: groups
- name: X-Forwarded-User
  values:
  - claim: user
- name: X-Forwarded-Email
  values:
  - claim: email
- name: X-Forwarded-Preferred-Username
  values:
  - claim: preferred_username
server:
  BindAddress: ""
  SecureBindAddress: :443
  TLS:
    Cert:
      fromFile: /etc/ssl/certs/fullchain.pem
    CipherSuites: null
    Key:
      fromFile: /etc/ssl/private/privkey.pem
    MinVersion: ""
metricsServer:
  BindAddress: ""
  SecureBindAddress: ""
  TLS: null
providers:
- ADFSConfig: {}
  azureConfig:
    graphGroupField: displayName
    tenant: {tenant-id}
  bitbucketConfig: {}
  clientID: {client-id}
  clientSecret: {client-secret}
  githubConfig: {}
  gitlabConfig: {}
  googleConfig: {}
  id: Microsoft
  keycloakConfig: {}
  loginGovConfig: {}
  loginURL: https://login.microsoftonline.com/{tenant-id}/v2.0/authorize
  loginURLParameters:
  - default:
    - force
    name: approval_prompt
  name: Microsoft
  redeemURL: https://login.microsoftonline.com/{tenant-id}/v2.0/token
  oidcConfig:
    audienceClaims:
    - aud
    emailClaim: email
    groupsClaim: groups
    insecureSkipNonce: true
    issuerURL: https://login.microsoftonline.com/{tenant-id}/v2.0
    jwksURL: https://login.microsoftonline.com/{tenant-id}/v2.0/keys
  provider: oidc
  scope: openid email
```

For troubleshooting which headers are passed from one container to the next I used the below command.  I though it might be helpful for anyone else troubleshooting communications between the proxy and the app:
```
docker run --tty -v /srv/multitool/data:/data --net=container:srv-app-1 wbitt/network-multitool tcpdump -w /data/test.pcap
```
