### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by jasonhjohnson** [bionic-gpt/bionic-gpt#104]
Hi,

When I try to run `docker-compose up` I receive the following error:

no matching manifest for linux/arm64/v8 in the manifest list entries

I'm on an Apple M1

Thanks in advance!
Jason

**Comment by ianpurton** [comment]
Looks like docker is trying to pull ARM images and we don't have those images.

I've created a docker-compose.yml with the `platform: linux/amd64` tag added.

Could you let us know if this works?

```yml
services:

  llm-api:
    platform: linux/amd64
    image: ghcr.io/bionic-gpt/llama-2-7b-chat:1.0.2

  embeddings-api:
    platform: linux/amd64
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.2.2
    command: --model-id BAAI/bge-small-en-v1.5

  # Handles parsing of multiple documents types.
  unstructured:
    platform: linux/amd64
    image: downloads.unstructured.io/unstructured-io/unstructured-api:c30a2b8
    ports:
      - "8000:8000"

  # Handles routing between the application, barricade and the LLM API
  envoy:
    image: ghcr.io/bionic-gpt/bionicgpt-envoy:1.3.1
    ports:
      - "7800:7700"

  # Postgres pre-loaded with pgVector
  # To connect outside docker `docker compose exec db psql -U postgres`
  db:
    image: ankane/pgvector
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: finetuna
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sets up our database tables
  migrations:
    image: ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.3.1
    platform: linux/amd64
    environment:
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  # Barricade handles all /auth routes for user sign up and sign in.
  barricade:
    image: purtontech/barricade
    platform: linux/amd64
    environment:
        # This secret key is used to encrypt cookies.
        SECRET_KEY: 190a5bf4b3cbb6c0991967ab1c48ab30790af876720f1835cbbf3820f4f5d949
        DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable
        FORWARD_URL: app
        FORWARD_PORT: 7703
        REDIRECT_URL: /app/post_registration
        RUST_LOG: warn
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  pipeline-job:
    image: ghcr.io/bionic-gpt/bionicgpt-pipeline-job:1.3.1
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  app:
    image: ghcr.io/bionic-gpt/bionicgpt:1.3.1
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
```
