### ISSUE TITLE
Multilingual embeddings

### ISSUE THREAD

**Issue by Pitachoo11** [bionic-gpt/bionic-gpt#144]
Hi!

I'm looking for alternative embeddings model for my purposes. Is there any solution to change default setup
and connect other pre-trained multilingual model. BionicGPT documentation does not give enough info ho to do it.

What are the options here?
*****************************
### My current yaml config taken from https://localai.io/integrations/bionic-gpt/

```yaml
 Our axum server delivering our user interface
  embeddings-job:
    image: ghcr.io/purton-tech/bionicgpt-embeddings-job:1.1.10
    environment:
      OPENAI_ENDPOINT: http://X.X.X.X:5000 (where I expose my LLM API)
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
```

*****************************
Uploaded document processing is doing their job (I see it in STATUS column of the dataset Tab), but I do not understand what and where is going on in fact.

Thank you in advance for any help with this!
