### ISSUE TITLE
Embeddings slow on CPU

### ISSUE THREAD

**Issue by ianpurton** [bionic-gpt/bionic-gpt#152]
Used to be much faster when we use local ai.

- [ ] try the local ai version again.
- [ ] https://localai.io/howtos/easy-setup-embeddings/

```yml

services:
  api:
    image: quay.io/go-skynet/local-ai:v1.40.0
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models
      - ./images/:/tmp/generated/images/
    command: ["/usr/bin/local-ai" ]
```

**Comment by andzejsp** [comment]
whenever i try to launch this i get :
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

I have nvidia gpu 1080ti. Stable difussion works on it, linux, ubuntu, so why this does not?

**Comment by ianpurton** [comment]
@andzejsp You're probably missing the nvidia container toolkit. https://github.com/NVIDIA/nvidia-container-toolkit

**Comment by andzejsp** [comment]
> @andzejsp You're probably missing the nvidia container toolkit. https://github.com/NVIDIA/nvidia-container-toolkit

thanks, added, now compose loads, but still gpu is not being used, it just sits idle while cpu processes the prompts. What kind of other configuration do i need to do to make it work on gpu?

compose.yaml:
```yaml
services:

  llm-api:
    image: ghcr.io/bionic-gpt/llama-2-7b-chat:1.0.4
    platform: linux/amd64

  # embeddings-api:
  #   image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.2.2
  #   platform: linux/amd64
  #   command: --model-id BAAI/bge-small-en-v1.5
  embeddings-api:
    image: ghcr.io/huggingface/text-embeddings-inference:0.2.2
    platform: linux/amd64
    command: --model-id BAAI/bge-small-en-v1.5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  # Handles parsing of multiple documents types.
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:c30a2b8
    platform: linux/amd64
    ports:
      - "8000:8000"

  # Handles routing between the application, barricade and the LLM API
  envoy:
    image: ghcr.io/bionic-gpt/bionicgpt-envoy:1.4.14
    platform: linux/amd64
    ports:
      - "7800:7700"

  # Postgres pre-loaded with pgVector
  # To connect outside docker `docker compose exec db psql -U postgres`
  db:
    image: ankane/pgvector
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: finetuna
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sets up our database tables
  migrations:
    image: ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.4.14
    platform: linux/amd64
    environment:
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  # Barricade handles all /auth routes for user sign up and sign in.
  barricade:
    image: purtontech/barricade
    platform: linux/amd64
    environment:
        # This secret key is used to encrypt cookies.
        SECRET_KEY: 190a5bf4b3cbb6c0991967ab1c48ab30790af876720f1835cbbf3820f4f5d949
        DATABASE_URL: postgresql://ft_authentication:testpassword@db:5432/postgres?sslmode=disable
        FORWARD_URL: app
        FORWARD_PORT: 7703
        REDIRECT_URL: /app/post_registration
        RUST_LOG: warn
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  pipeline-job:
    image: ghcr.io/bionic-gpt/bionicgpt-pipeline-job:1.4.14
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  app:
    image: ghcr.io/bionic-gpt/bionicgpt:1.4.14
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
```
