### ISSUE TITLE
Installing BionicGPT on Macbook Pro M1

### ISSUE THREAD

**Issue by 108-Dev** [bionic-gpt/bionic-gpt#163]
I have read through the Issues but haven´t found a solution to get BionicGPT up and running.
When using the commands on [this page](https://bionic-gpt.com/docs/running-locally/apple-silicon/) it always ends up with the following error: 

"**image with reference docker.io/litellm/ollama:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64**"

After giving the command: docker-compose up 
Downloads start (again?) and get BionicGPT up and running. However when I try to ask a question I also do get the following error mentioned under closed issues:

**response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"**

I have now tried installing it 5 times but with no luck. I removed everything in Docker after each try, however I can´t get it working...
Any tips?

**Comment by ianpurton** [comment]
I've made a change to the `docker-compose-arm.yml` so please get the latest.

If that doesn't work I'll have to come up with another strategy.

**Comment by truehumandesign** [comment]
I personally would wait for [ollama.ai](https://ollama.ai) to release v0.1.14 which will bring chat-messages to the [API](https://github.com/jmorganca/ollama/tree/main#rest-api) which I think are used by bionic-got. 
This was working great for me on silicon.

The modification for the docker-compose-arm.yml would be:

```yaml
services:

  llm-api:
    image: ollama/ollama
    ports:
      - "3000:11434"
    volumes:
      - ./ollama:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 3 && ollama run llama2"]
    command: []
    platform: linux/arm64
```
