### ISSUE TITLE
Problem with Mistral on gpu

### ISSUE THREAD

**Issue by freakontrol** [bionic-gpt/bionic-gpt#174]
Hi there,
I was testing this project and it worked perfectly with the default compose and Llama2 model, but when i use the compose-gpu model, i get no more a chat llm but a response that is a continuation of my question. What I'm missing?

example:

**I expected this**
_me_: Hi
_Llama2 (cpu)_: Hello! How can I assist you today?

**But I'm receiving this**
_me_: Hi
_Mistral (gpu)_: I need help with making a function that counts the number of positive integers in a given list.

Thank you in advance.

PS: I'm using this model "TheBloke/OpenHermes-2.5-neural-chat-7B-v3-2-7B-AWQ"

**Comment by ianpurton** [comment]
Hi.

Looking at the model https://huggingface.co/TheBloke/OpenHermes-2.5-neural-chat-7B-v3-2-7B-AWQ

I can see the prompt template below

```
<|im_start|>system
{system_message}<|im_end|>
<|im_start|>user
{prompt}<|im_end|>
<|im_start|>assistant
```

TGI https://github.com/huggingface/text-generation-inference doesn't do anything with the chat message to convert it to this format.

However,  LiteLLM should do this conversion for us.

Did you specify the model in LiteLLM too?

**Comment by ianpurton** [comment]
@freakontrol Update. I've changed the documentation to simplify GPU setup and added a section on changing the model.

https://bionic-gpt.com/docs/running-locally/gpu-setup/

**Comment by freakontrol** [comment]
I've been able to make it work with the following config:

```
  llm-api-mistral:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    command: --model huggingface/teknium/OpenHermes-2.5-Mistral-7B --api_base http://tgi-mistral/generate_stream --host 0.0.0.0 --port 3333
    platform: linux/amd64
```

But now i see the prompt in the responses:

Me: Hi
LLM: im_start|>bot Hello! Is there anything more you'd like to know or discuss? I'm here to help you with your queries. <|im_end|>
