### ISSUE TITLE
docker-compose migrations fail

### ISSUE THREAD

**Issue by bsu3338** [bionic-gpt/bionic-gpt#183]
I copied the docker with
curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose.yml

ran docker compose up -d

The migrations container does not seem to be connecting to the database.  I can confirm that postgres is running with:
docker compose exec db psql -U postgres

docker logs give:
migrations-1 |Error: dial tcp 10.4.1.14:5432: connect: connection refused
INFO[0002] Container "srv-migrations-1" exited

**Comment by ianpurton** [comment]
@bsu3338 I've just tried it on linux and it worked fine, what system are you on?

**Comment by truehumandesign** [comment]
@bsu3338 its working fine on macOS too

**Comment by bsu3338** [comment]
I am still not sure of the root cause.  I am using alpine linux(3.19)/containerd(containerd-1.7.10)/nerdctl (1.7.1). I added the below and was able to connect to the database.

```
  pgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4:latest
    volumes:
      - /srv/pgadmin/data:/var/lib/
    ports:
      - "5050:5050"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dbadmin@corp.net
      PGADMIN_DEFAULT_PASSWORD: RandomPassword
      PGADMIN_LISTEN_PORT: 5050

```

After connecting with pgadmin, I ran **docker compose start migrations**
