### ISSUE TITLE
External model integration

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#190]
Hello, i used OLLAMA to add a new model (mistral for example) : 
services:
```
  llm-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    command: ["/bin/sh", "-c", "pip install async_generator && litellm --model ollama/mistral --api_base http://host.docker.internal:11434 --host 0.0.0.0 --port 3000"]
    entrypoint: []
    platform: linux/amd64
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

after in the model setup , i added a new model like this ; 

mistral | http://host.docker.internal:3000 | Large Language Model | 7 Billion | 2048
and 
mistral | http://host.docker.internal:11434 | Large Language Model | 7 Billion | 2048

but in the chat, i tested with hello , i get  : Error occurred while generating.
