### ISSUE TITLE
Testing K8's and new TGI.

### ISSUE THREAD

**Issue by 9876691** [bionic-gpt/bionic-gpt#338]
Looks like TGI now have support for Open AI API.

To test this we need to change the `docker-compose-gpu.yml` to something like the one below.

```yml
services:

  llm-api:
    image: ghcr.io/huggingface/text-generation-inference:sha-0eabc83
    command: --model-id TheBloke/zephyr-7B-beta-AWQ --max-batch-prefill-tokens 2048 --quantize awq
    volumes:
      - ./models:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

## Tests (docker compose)

- Is it still working i.e. does the container start and model load.
- Can we call it from the UI.

## Testing API

```
curl -N http://localhost:8080/v1/chat/completions   -H "content-type: application/json"   -d '{
     "model": "llama-2-7b",
     "messages": [{"role": "user", "content": "Give me some tips on writing job postings"}]}'
```

## Testing CPU
```sh
model=HuggingFaceH4/zephyr-7b-beta
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --shm-size 1g --memory=6m -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:sha-0eabc83 --model-id $model --quantize awq --disable-custom-kernels
```

## Download and Quantize Model

```sh
model=HuggingFaceH4/zephyr-7b-beta
volume=$PWD/data
docker run -it --gpus all --entrypoint text-generation-server -v $volume:/data ghcr.io/huggingface/text-generation-inference:sha-0eabc83 quantize $model /data
```

**Comment by kulbinderdio** [comment]
non streaming

curl 127.0.0.1:8080/generate \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}' \
    -H 'Content-Type: application/json'

**Comment by 9876691** [comment]
We need this fixed https://github.com/huggingface/text-generation-inference/issues/1545

**Comment by 9876691** [comment]
Testing new `docker-compose-gpu.yml`

```
services:

  llm-api:
    image: ghcr.io/huggingface/text-generation-inference:1.4.2
    command: --port 11434 --model-id TheBloke/zephyr-7B-beta-AWQ --max-batch-prefill-tokens 2048 --quantize awq
    volumes:
      - ./models:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
