### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by SQLExceptionPhil** [bionic-gpt/bionic-gpt#348]
### Describe your issue

When sending a chat message in bionic-gpt I receive following error 

```
Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at streaming-chat.ts:72:43
    at Array.forEach (<anonymous>)
    at r.streamResult (streaming-chat.ts:56:21)
```

The error occures because of the TextDecoderStream reader. It reads some amount of text from the server and it is not guaranteed that the last "data: .." contains valid json. Seen here:

```
....
data: {"choices":[{"delta":{"content":"phony"},"finish_reason":null,"index":0}],"created":1706281613,"id":"chatcmpl-hn6GSlxFGD9FLQsheVIv5PbNk6A5cccZ","model":"Mixtral","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" of"},"finish_reason":null,"index":0}],"created":1706281613,"id":"chatcmpl-ogxWJugUFn5g0bg7oUdAOYcF1DIQqgmS","model":"Mi
VM13181:19 value-size 4096
```
next streamed chunk:
```
value xtral","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":" micro"},"finish_reason":null,"index":0}],"created":1706281613,"id":"chatcmpl-TxV0TtsRVrN8ZUdE9S614rnCc7sqwiN3","model":"Mixtral","object":"chat.completion.chunk"}

data: {"choices":[{"delta":{"content":"services"},"finish_reason":null,"index":0}],"created":1706281613,"id":"chatcmpl-z5YnHBlaRg87wMqFTIkmjYBAiSlnofSl","model":"Mixtral","object":"chat.completion.chunk"}
...
```

I think a possible solution could be to buffer the last data value if it is not in correct json format and append the next occuring data value to the buffer and check again if it is a valid json object. With the current state of the code it just returns an error "Error occurred while generating."

I am not sure if this is a follow up error of this behaviour but the chat also doesn't update while it is streaming and is sending multiple requests to the backend (requests made to 48 - after clicking Send Message once). 
![image](https://github.com/bionic-gpt/bionic-gpt/assets/35815130/588e6243-9538-40e1-9843-218853b62d46)
LLM-Server logs after clicking it once:
![image](https://github.com/bionic-gpt/bionic-gpt/assets/35815130/e1208185-50ff-427f-9af9-e579adc874de)

### Describe your setup/startup scripts

I created multiple kubernetes deployments corresponding to the services in the docker-compose.yaml file. Because I was just testing the software I didn't use any oicd provider instead used an nginx infront of the app and always send the needed headers:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen        80;
      client_max_body_size 2G;
      proxy_send_timeout  7d;
      proxy_read_timeout  7d;

      server_tokens off;
      add_header X-Frame-Options "SAMEORIGIN";
      add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
      add_header Content-Security-Policy "default-src 'self' 'unsafe-eval' http: https: data: blob: ws: wss: 'unsafe-inline'" always;
      add_header X-XSS-Protection "1; mode=block";
      add_header Set-Cookie "Path=/; HttpOnly; Secure";

      location / {
        proxy_set_header X-Forwarded-User "admin";
        proxy_set_header X-Forwarded-Email "admin@example.com";
        proxy_pass      http://app.bionic-gpt.svc.cluster.local:7703;
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80

```

As a inference server I used llama.cpp also running inside a k8s cluster:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp
spec:
  selector:
    matchLabels:
      app: llama-cpp
  template:
    metadata:
      labels:
        app: llama-cpp
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: llama-cpp
          image: devel/llama-cpp-server:20240126-03
          command: ["/llama-app/llama.cpp/build/bin/server"]
          args:
            [
              "--model",
              "/app/models/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf",
              "-ngl",
              "33",
              "-c",
              "8192",
              "-t",
              "8",
              "--port",
              "8080",
              "--host",
              "0.0.0.0",
              "-cb",
              "-np",
              "8",
            ]
          resources:
            limits:
              memory: "64Gi"
              cpu: "8"
              nvidia.com/gpu: "2"
          ports:
            - containerPort: 8080
              name: api
```

### Steps to reproduce

1. Setup bionic-gpt
2. use llama.cpp as inference server
3. Go to Chat Console
4. Let the AI write something longer

### Any additional information

Related: https://github.com/bionic-gpt/bionic-gpt/issues/318
