### ISSUE TITLE
Error occurred while generating.

### ISSUE THREAD

**Issue by brunoAmado** [bionic-gpt/bionic-gpt#351]
### Describe your issue

trying bionic-gpt to a multilingual RAG. I embed documentation using "intfloat/multilingual-e5-large" and directly with the "Unbabel/TowerInstruct-7B-v0.1" model but trying the chat I always have "Error occurred while generating". Even changing Trim Ratio

### Describe your setup/startup scripts

```
   llmTowerInstruct-7B-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    command:
      - /bin/sh
      - -c
      - |
        pip install async_generator
        litellm --model huggingface/Unbabel/TowerInstruct-7B-v0.1 --api_base http://${LOCALHOST_IP}:8102/generate_stream --host 0.0.0.0 --port 3307
    entrypoint: [ ]
    platform: linux/amd64
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "3307:3307"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    tgi-me5l-gpu-api:
    image: ghcr.io/huggingface/text-embeddings-inference:latest
    platform: linux/amd64
    command: --model-id intfloat/multilingual-e5-large
    volumes:
      - ./models:/data
    ports:
      - 8011:8011
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  tgi-towerinstruct-gpu:
    image: ghcr.io/huggingface/text-generation-inference:latest
    command: --model-id Unbabel/TowerInstruct-7B-v0.1 --quantize eetq --num-shard 1 --max-batch-prefill-tokens 256 --max-input-length 256
    volumes:
      - ./models:/data
    ports:
      - 8102:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
```

### Steps to reproduce

![Captura de ecrã 2024-01-29 131448](https://github.com/bionic-gpt/bionic-gpt/assets/5504321/c8be5fd5-3164-41d7-a545-054452bbe036)
