### ISSUE TITLE
Error code 422 - while testing with API

### ISSUE THREAD

**Issue by felixepiklah** [bionic-gpt/bionic-gpt#358]
### Describe your issue

Got "Error code status = 422 Unprocessable Entity, message = error trying to connect: dns error: failed to lookup address information: Name does not resolve" when trying to call the api from Postman app.

Happened on both:
+ v1/models
+ v1/chat/completions

### Describe your setup/startup scripts

docker-compose -f docker-compose.yml -f docker-compose-gpu.yml upa

### Steps to reproduce

1 - I setup the OpenVPN for both clients and server.
a - Cloud VPS -> This is a VPS acting as a OpenVPN server. IP: 10.8.0.1
b - GPU PC (A) -> BionicGPT app/api are runing on an OpenVPN client (Assume that firewall is disable and other VPN client can access to this PC). IP: 10.8.0.2
c -  A laptop (B) (another VPN client). IP: 10.8.0.3 - It can access to BionicGPT UI from 10.8.0.2:7800

2 -  Make sure connection and ports are not blocked.
3 - Check if Laptop (B) can access BionicGPT from PC (A) via 10.8.0.2:7800.
4 - Create API key
5 - Check if can call the API with postman or curl -> Failed.
status = 422 Unprocessable Entity, message = error trying to connect: dns error: failed to lookup address information: Name does not resolve

### What was the expected result?

I call BionicGPT API can return the result.

### Any additional information

Log file:
[issue.log](https://github.com/bionic-gpt/bionic-gpt/files/14182745/issue.log)
Docker file:
[docker-compose-gpu.zip](https://github.com/bionic-gpt/bionic-gpt/files/14182776/docker-compose-gpu.zip)

**Comment by brunoAmado** [comment]
what happen if you add dns like the docker-compose-ollama.yml

```
  llm-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    command: ["/bin/sh", "-c", "pip install async_generator && litellm --model ollama/llama2 --api_base http://host.docker.internal:11434 --host 0.0.0.0 --port 3000"]
    entrypoint: []
    platform: linux/amd64
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

or like docker-compose-hardened:

```
    # False DNS so the service can't make DNS lookups.
    dns: 0.0.0.0
```
