### ISSUE TITLE
Ingress not installed for Docker Desktop

### ISSUE THREAD

**Issue by 9876691** [bionic-gpt/bionic-gpt#438]
K3s comes with an ingress operator but not docker desktop.

- Install K3s without the ingress operator
- Install nginx ingress

Working nginx config

```
cat <<EOF | kubectl apply -n bionic-gpt -f-
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # We need to set the buffer size or keycloak won't let you register
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    # We need toi set this as the max size for document upload
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  name: bionic-gpt-ingress
spec:
  rules:
  - http:
      paths:
      - path: /oidc
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 7910
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 7900
EOF
```
