### ISSUE TITLE
Gemini integration

### ISSUE THREAD

**Issue by tiswas247** [bionic-gpt/bionic-gpt#694]
## Gemini expects capital H on host

```sh
kubectl apply -n bionic-gpt -f bionic-gpt/infra-as-code/lite-llm.yaml
```

## Lite LLM Yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
data:
  config.yaml: |
      model_list:
        - model_name: gemini-pro
          litellm_params:
            model: gemini/gemini-1.5-pro
            api_key: API_KEY
            
        - model_name: gemini-1.5-flash-001
          litellm_params:
            model: gemini-1.5-flash-001
            api_base: https://generativelanguage.googleapis.com/v1beta
            api_key: API_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest # it is recommended to fix a version generally
        args:
          - "--config"
          - "/app/config.yaml"
          - "--detailed_debug"
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file
---
# Service to expose Lite llm
apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  type: ClusterIP
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
```
