### ISSUE TITLE
Lightweight local Bionic doesn't seem to work?

### ISSUE THREAD

**Issue by frankpepermans** [bionic-gpt/bionic-gpt#724]
### Describe your issue

Hi all,

I'm very eager to try out Bionic-GPT and found this article on how to set it up locally: https://bionic-gpt.com/docs/running-locally/docker-compose/

However, the `docker-compose.yaml` did not work: I had to change a dependency for `bionicgpt-envoy` to `1.8.31` first.

After doing so, I could run it containerized, but when trying to access the localhost, I get this error: ```upstream connect error or disconnect/reset before headers. reset reason: connection failure```.

### Describe your setup/startup scripts

```yaml
# Do not expose this configuration to the internet. This is an
# example configuration so that you can try out Bionic GPT.
#
# This is NOT a production configuration.
services:

  llm-api:
    image: ghcr.io/bionic-gpt/llama-3-8b-chat:1.1.3
    platform: linux/amd64

  embeddings-api:
    image: ghcr.io/bionic-gpt/bionicgpt-embeddings-api:cpu-0.6
    platform: linux/amd64

  # Document parsing, OCR and chunking.
  chunking-engine:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:4ffd8bc
    platform: linux/amd64

  # Postgres pre-loaded with pgVector
  # To connect outside docker `docker compose exec postgres psql -U postgres`
  postgres:
    image: ankane/pgvector
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # Handles routing between our containers
  envoy:
    image: ghcr.io/bionic-gpt/bionicgpt-envoy:1.8.31
    ports:
      - "3000:7700"

  # Configure Authn Proxy to listen on port 9090 and reverse proxy nginx on port 80.
  barricade:
    image: purtontech/barricade:1.2.10
    environment:
        # This secret key is used to encrypt cookies.
        SECRET_KEY: 190a5bf4b3cbb6c0991967ab1c48ab30790af876720f1835cbbf3820f4f5d949
        DATABASE_URL: postgresql://postgres:testpassword@postgres:5432/bionic-gpt?sslmode=disable
        REDIRECT_URL: /app/post_registration
        USER_TABLE_NAME: 'barricade_users'
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  # Sets up our database tables
  migrations:
    image: ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.9.2
    platform: linux/amd64
    environment:
      DATABASE_URL: postgresql://postgres:testpassword@postgres:5432/bionic-gpt?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
  
  # Parses documents into chunks and creates embeddings.
  rag-engine:
    image: ghcr.io/bionic-gpt/bionicgpt-rag-engine:1.9.2
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://bionic_application:testpassword@postgres:5432/bionic-gpt?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  app:
    image: ghcr.io/bionic-gpt/bionicgpt:1.9.2
    platform: linux/amd64
    environment:
      SIGNOUT_URL: /auth/sign_out
      ENABLE_BARRICADE: 1
      APP_DATABASE_URL: postgresql://bionic_application:testpassword@postgres:5432/bionic-gpt?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
```

### Steps to reproduce

1. run `docker-compose up`
2. navigate to localhost in a browser

### What was the expected result?

The web-app would load
